# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# title: Disha Kamale # Website name
baseURL: 'https://dishakamale.github.io/robotics/' # Website URL
languageCode: 'en-us'
title: 'Disha Kamale'

build:
  buildStats:
    enable: true
  cssMinify: true

module:
  proxy: direct
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5

# Updated outputs section
outputs:
  home: 
    - HTML
    - RSS
    - JSON
    - WebAppManifest
    - headers
    - redirects
    - SITEMAP
  section: 
    - HTML
    - RSS

outputFormats:
  SITEMAP:
    mediaType: "application/xml"
    baseName: "sitemap"
    isHTML: false

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true

# imaging:
#   resampleFilter: lanczos
#   quality: 100
#   anchor: smart
imaging:
  resampleFilter: lanczos
  quality: 100
  anchor: smart
params:
  features:
    avatar:
      size: large 
      quality: 100
      force_resize: false
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
# sitemap:
#   _merge: deep
minify:
  _merge: deep
